services:
  app:
    image: node:19
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

  codegen:
    image: nebulit/codegen
    profiles:
      - tools
    volumes:
      - .:/workspace
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true
